//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by FelixPackageUI.rc
//
#define IDS_OFFICIALNAME                100
#define IDS_ASSEMBLER_PROP_PAGE_TITLE   101
#define IDD_REPORT_ERROR                101
#define IDS_PRODUCTDETAILS              102
#define IDS_COMPANYNAME                 103
#define IDS_VERSION                     104
#define IDS_DEBUGGING_PROP_PAGE_TITLE   105
#define IDS_RENAMEFILEALREADYEXISTS     106
#define IDS_NOT_SUPPORTED_WHILE_SIMULATOR_RUNNING 107
#define IDS_PRE_BUILD_PROP_PAGE_TITLE   108
#define IDS_POST_BUILD_PROP_PAGE_TITLE  109
#define IDS_PRE_BUILD_CMD_LINE_DESCRIPTION 110
#define IDS_POST_BUILD_CMD_LINE_DESCRIPTION 111
#define IDS_PRE_POST_BUILD_DESCRIPTION_DESCRIPTION 112
#define IDS_NEW_FOLDER_NAME             113
#define IDS_ITEM_ALREADY_EXISTS_IN_LOCATION 114
#define IDS_NAME_ALREADY_EXISTS         115
#define IDS_FILE_ALREADY_IN_PROJECT     116
#define IDS_GENERATED_FILES             117
#define IDS_PREINCLUDE                  118
#define IDS_POSTINCLUDE                 119
#define IDS_PROPERTY_EVALUATES_TO       120
#define IDS_GEN_PRE_POST_MESSAGE_DONE   121
#define IDS_GEN_PRE_POST_MESSAGE_FAIL   122
#define IDS_GEN_PRE_POST_MESSAGE        123
#define IDS_REMOVING_GEN_FILES          124
#define IDS_UNK_NUM_FORMAT              125
#define IDS_UNK_EXPRESSION              126
#define IDS_GENERAL_PROP_PAGE_TITLE     127
#define IDS_GENERAL_PROPS_OUTPUT_NAME_NAME 128
#define IDS_GENERAL_PROPS_OUTPUT_NAME_DESCRIPTION 129
#define IDS_GENERAL_PROPS_PROJ_NAME_NAME 130
#define IDS_GENERAL_PROPS_PROJ_NAME_DESCRIPTION 131
#define IDS_ASM_PROPS_ENTRY_POINT_ADDR_NAME 132
#define IDS_ASM_PROPS_ENTRY_POINT_ADDR_DESC 133
#define IDS_GENERAL_PROPS_OUTPUT_DIR_NAME 134
#define IDS_GENERAL_PROPS_OUTPUT_DIR_DESC 135
#define IDS_NO_BUILD_TOOL_ASM_FILES     136
#define IDB_IMAGES                      300
#define IDI_PACKAGE_ICON                400
#define IDI_SPECTRUM                    401
#define IDD_DIALOG_COMMAND_LINE_EDITOR  405
#define IDC_EDIT_ERROR_REPORT           1000
#define IDC_BUTTON_SEND                 1001
#define IDC_BUTTON_DONT_SEND            1002
#define IDC_EDIT_EMAIL_ADDRESS          1003
#define IDC_EDIT_COMMANDS               1005
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        406
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1006
#define _APS_NEXT_SYMED_VALUE           402
#endif
#endif
