import "oaidl.idl";
import "ocidl.idl";

[uuid(1C657EB2-AB87-45D5-B8F7-8A2BC5E54CA8)]
library UITestsLib
{
	importlib("stdole2.tlb");

	[object, uuid(F9E501BD-5CA7-4088-8EB8-4DC03A1ADB0F), dual, nonextensible, pointer_default(unique)]
	interface ITestPropertyNotifySink : IDispatch
	{
		HRESULT IsChanged (DISPID dispid);
	}
}
