
import "docobj.idl";
#include "dispids.h"

//cpp_quote("#ifdef __midl")
typedef DWORD VSITEMID;
typedef LONG VSHPROPID;
//cpp_quote("#endif")

[uuid(C045D7BF-B8F2-4F6E-8E4A-0D4DF3322AC7)]
library ATLProject1Lib
{
	importlib("stdole2.tlb");

	interface IProjectNodeProperties;
	interface IProjectConfigAssemblerProperties;
	interface IProjectConfigDebugProperties;
	interface ICommandLineList;
	interface IProjectConfigPrePostBuildProperties;

	[uuid(15412FDD-6A57-420C-933E-0A89A1DF497D)]
	enum OutputFileType { Binary, Sna };

	[object, uuid(A6F7B8F9-7FD3-4819-963A-5238B32F4123), dual, nonextensible, pointer_default(unique)]
	interface IProjectConfigProperties : IDispatch
	{
		[id(dispid__name), propget] HRESULT __id ([out, retval] BSTR* value);

		[id(dispidAssemblerProperties), propget] HRESULT AssemblerProperties ([out, retval] IProjectConfigAssemblerProperties** ppProps);

		// Same object as AssemblerProperties, kept for backward compatibility
		[id(dispidGeneralProperties), propput] HRESULT GeneralProperties (IProjectConfigAssemblerProperties* pDispatch);

		[id(dispidDebuggingProperties), propget] HRESULT DebuggingProperties ([out, retval] IProjectConfigDebugProperties** ppProps);

		[id(dispidPreBuildProperties), propget, helpstring("The implementation allocates this object during creation; it is always non-NULL.")]
		HRESULT PreBuildProperties ([out, retval] IProjectConfigPrePostBuildProperties** ppProps);
		
		[id(dispidPostBuildProperties), propget, helpstring("The implementation allocates this object during creation; it is always non-NULL.")]
		HRESULT PostBuildProperties ([out, retval] IProjectConfigPrePostBuildProperties** ppProps);

		[id(dispidConfigName), propget] HRESULT ConfigName ([out, retval] BSTR* pbstr);
		[id(dispidConfigName), propput] HRESULT ConfigName (BSTR pbstr);

		[id(dispidPlatformName), propget] HRESULT PlatformName ([out, retval] BSTR* pbstr);
		[id(dispidPlatformName), propput] HRESULT PlatformName (BSTR pbstr);
	};

	[object, uuid(6109C4FD-C067-4120-9853-6A2D6682BCB0), dual, nonextensible, pointer_default(unique)]
	interface IProjectConfigAssemblerProperties : IDispatch
	{
		[id(dispid__name), propget] HRESULT __id ([out, retval] BSTR* value);

		[id(dispidOutputFileType), bindable, propget]
		HRESULT OutputFileType ([out, retval] enum OutputFileType* value);
		[id(dispidOutputFileType), bindable, propput]
		HRESULT OutputFileType (enum OutputFileType value);

		[id(dispidBaseAddress), bindable, propget] HRESULT BaseAddress ([out, retval] unsigned long* value);
		[id(dispidBaseAddress), bindable, propput] HRESULT BaseAddress (unsigned long value);

		[id(dispidEntryPointAddress), bindable, propget] HRESULT EntryPointAddress ([out, retval] BSTR* pbstrAddress);
		[id(dispidEntryPointAddress), bindable, propput] HRESULT EntryPointAddress (BSTR bstrAddress);

		[id(dispidSaveListing), bindable, propget] HRESULT SaveListing ([out, retval] VARIANT_BOOL* save);
		[id(dispidSaveListing), bindable, propput] HRESULT SaveListing (VARIANT_BOOL save);

		// It's called SaveListingFilename (as opposed to ListingFilename) so it appears in the property grid right after SaveListing.
		[id(dispidListingFilename), bindable, propget] HRESULT SaveListingFilename ([out, retval] BSTR* pFilename);
		[id(dispidListingFilename), bindable, propput] HRESULT SaveListingFilename (BSTR filename);

		HRESULT GetOutputFileName ([out, retval] BSTR* pbstr);
		HRESULT GetSldFileName ([out, retval] BSTR* pbstr);
	};

	[uuid(A6C45AD3-6F11-4116-A65D-9083381843D8)]
	enum LaunchType { PrintUsr, RandomizeUsr, ResetAndJump };

	[object, uuid(D529C72D-D7B3-40EF-9FF9-31595F4518D2), dual, nonextensible, pointer_default(unique)]
	interface IProjectConfigDebugProperties : IDispatch
	{
		[id(dispid__name), propget] HRESULT __id ([out, retval] BSTR* value);

		// "Selects the launch method: PRINT USR from Basic, RANDOMIZE USR from Basic, or jump right after reset."
		[id(dispidLaunchType), bindable, propget, helpstring("This setting is currently not implemented; the launch type is always PRINT USR. It will be implemented in a future release.")]
		HRESULT LaunchType ([out, retval] enum LaunchType* value);
		[id(dispidLaunchType), bindable, propput]
		HRESULT LaunchType (enum LaunchType value);
	};

	[object, uuid(681706E6-D0E3-4794-92E4-B87F9690516B), dual, nonextensible, pointer_default(unique)]
	interface ICommandLineList : IDispatch
	{
		[id(dispidCommandLine), propget]
		HRESULT CommandLine ([out, retval] BSTR* value);
		[id(dispidCommandLine), propput]
		HRESULT CommandLine (BSTR value);

		[id(dispidDescription), propget]
		HRESULT Description ([out, retval] BSTR* value);
		[id(dispidDescription), propput]
		HRESULT Description (BSTR value);
	};

	[object, uuid(41E55107-3759-4775-9D7C-1AA568536E46), dual, nonextensible, pointer_default(unique)]
	interface IProjectConfigPrePostBuildProperties : ICommandLineList
	{
	};

	// IID Same as the pkgdef entry [$RootKey$\Projects\{D438161C-F032-4014-BC5C-20A80EAFF59B}]
	[object, uuid(D438161C-F032-4014-BC5C-20A80EAFF59B), dual, nonextensible, pointer_default(unique)]
	interface IProjectNodeProperties : IDispatch
	{
		[id(dispid__name), propget] HRESULT __id ([out, retval] BSTR* value);

		[id(dispidConfigurations), propget] HRESULT Configurations ([out, ref, retval] SAFEARRAY(IDispatch*)* configs);
		[id(dispidConfigurations), propput] HRESULT Configurations (SAFEARRAY(IDispatch*) configs);

		[id(dispidItems), propget] HRESULT Items ([out, ref, retval] SAFEARRAY(IDispatch*)* items);
		[id(dispidItems), propput] HRESULT Items (SAFEARRAY(IDispatch*) items);

		[id(dispidProjectGuid), propget] HRESULT Guid ([out, retval] BSTR* value);
		[id(dispidProjectGuid), propput] HRESULT Guid (BSTR value);

		[id(dispidAutoOpenFiles), propget] HRESULT AutoOpenFiles ([out, retval] BSTR* pbstrFilenames);
		[id(dispidAutoOpenFiles), propput] HRESULT AutoOpenFiles ([in] BSTR bstrFilenames);

		HRESULT GetAutoOpenFiles (BSTR* pbstrFilenames);
	}

	[uuid(AB38EBF9-C445-45EB-8C14-8656CA98A741)]
	enum BuildToolKind { None, Assembler, CustomBuildTool };

	[object, uuid(8577A7D6-BE63-4D76-8D51-130E8218C065), dual, nonextensible, pointer_default(unique)]
	interface ICustomBuildToolProperties : ICommandLineList
	{
		[id(dispidOutputs), propget]
		HRESULT Outputs ([out, retval] BSTR* value);
		[id(dispidOutputs), propput]
		HRESULT Outputs (BSTR value);
	}

	[object, uuid(680DBE9B-ABED-41BE-8A26-30446EEC47FB), dual, nonextensible, pointer_default(unique)]
	interface IFileNodeProperties : IDispatch
	{
		[id(dispid__name), propget] HRESULT __id ([out, retval] BSTR* value);

		[id(dispidPath), propget, helpstring("Path relative to the project directory.")]
		HRESULT Path ([out, retval] BSTR* value);
		[id(dispidPath), propput]
		HRESULT Path (BSTR value);

		[id(dispidIsGenerated), propget] HRESULT IsGenerated ([out, retval] DWORD* is);
		[id(dispidIsGenerated), propput] HRESULT IsGenerated (DWORD is);

		[id(dispidBuildToolKind), propget]
		HRESULT BuildTool ([out, retval] enum BuildToolKind* value);
		[id(dispidBuildToolKind), propput]
		HRESULT BuildTool (enum BuildToolKind value);

		[id(dispidCustomBuildToolProps), propget]
		HRESULT CustomBuildToolProperties ([out, retval] ICustomBuildToolProperties** ppProps);
	}

	[object, uuid(9BBC87D3-F9EA-46E4-804F-2E7C0C1D365F), dual, nonextensible, pointer_default(unique)]
	interface IFolderNodeProperties : IDispatch
	{
		[id(dispid__name), propget] HRESULT __id ([out, retval] BSTR* value);

		[id(dispidFolderName), propget] HRESULT Name ([out, retval] BSTR* value);
		[id(dispidFolderName), propput] HRESULT Name (BSTR value);

		[id(dispidItems), propget] HRESULT Items ([out, ref, retval] SAFEARRAY(IDispatch*)* items);
		[id(dispidItems), propput] HRESULT Items (SAFEARRAY(IDispatch*) items);
	}

	[object, uuid(588F7F04-8B74-404D-A80B-F7CCE9FA3E27), dual, nonextensible, pointer_default(unique)]
	interface IFelixLaunchOptions : IDispatch
	{
		[id(dispidProjectDir), propget] HRESULT ProjectDir ([out, retval] BSTR* pbstr);
		[id(dispidProjectDir), propput] HRESULT ProjectDir (BSTR pbstr);

		[propget] HRESULT BaseAddress ([out, retval] DWORD* pdwAddress);
		[propput] HRESULT BaseAddress (DWORD dwAddress);

		[propget] HRESULT EntryPointAddress ([out, retval] DWORD* pdwAddress);
		[propput] HRESULT EntryPointAddress (DWORD dwAddress);
	}
};
